export {
    default as coursesReducer,
    INIT_CLASS,
    INIT_COURSE,
    addCourse,
    addCourses,
    clearCourses,
    removeCourse,
    removeCourses,
    setCourseFilter,
    setCourses,
    setCoursesPagination,
    setCoursesScreenHistory,
    setHasMoreCourses,
    setIsCourseDeleting,
    setIsCourseLoading,
    setIsCoursesLoading,
    setRefreshCourses,
    setSelectedClass,
    setSelectedCourse,
    updateCourse
} from './slice';