export const revisitsMessages = {
    ABOUT_MIN_LENGTH: 'La información de la persona debe tener al menos 10 caracteres.',
    ABOUT_REQUIRED: 'La información de la persona es requerida.',
    ADDED_SUCCESS: 'Ha agregado la revisita correctamente.',
    ADDRESS_MIN_LENGTH: 'La dirección debe tener al menos 10 caracteres.',
    ADDRESS_REQUIRED: 'La dirección es requerida.',
    COMPLETED_SUCCESS: 'Ha marcado como completa su revisita correctamente.',
    DELETED_SUCCESS: 'Ha eliminado la revisita correctamente.',
    EXPORTED_SUCCESS: 'Ha exportado sus revisitas correctamente. El archivo se encuentra en la carpeta de descargas de su dispositivo.',
    NEXT_VISIT_REQUIRED: 'La fecha de la último visita no puede estar vacía.',
    PERSON_MIN_LENGTH: 'El nombre de la persona debe tener al menos 2 caracteres.',
    PERSON_NAME_REQUIRED: 'El nombre de la persona es requerido.',
    UNSELECTED_COMPLETE: 'No hay una revisita seleccionada para completar.',
    UNSELECTED_DELETE: 'No hay una revisita seleccionada para eliminar.',
    UNSELECTED_UPDATE: 'No hay una revisita seleccionada para actualizar.',
    UPDATED_SUCCESS: 'Ha actualizado la revisita correctamente.',
}