export const revisitsMessages = {
    PERSON_NAME_REQUIRED: 'El nombre de la persona es requerido.',
    PERSON_MIN_LENGTH: 'El nombre de la persona debe tener al menos 2 caracteres.',
    ABOUT_REQUIRED: 'La información de la persona es requerida.',
    ABOUT_MIN_LENGTH: 'La información de la persona debe tener al menos 10 caracteres.',
    ADDRESS_REQUIRED: 'La dirección es requerida.',
    ADDRESS_MIN_LENGTH: 'La dirección debe tener al menos 10 caracteres.',
    NEXT_VISIT_REQUIRED: 'La fecha de la último visita no puede estar vacía.',
    UNSELECTED_COMPLETE: 'No hay una revisita seleccionada para completar.',
    COMPLETED_SUCCESS: 'Has marcado como completa tu revisita correctamente.',
    UNSELECTED_DELETE: 'No hay una revisita seleccionada para eliminar.',
    DELETED_SUCCESS: 'Has eliminado la revisita correctamente.',
    ADDED_SUCCESS: 'Has agregado la revisita correctamente.',
    UNSELECTED_UPDATE: 'No hay una revisita seleccionada para actualizar.',
    UPDATED_SUCCESS: 'Has actualizado la revisita correctamente.',
}