import {
    BUGFENDER_API_KEY,
    EMAILJS_FEEDBACK_TEMPLATE_ID,
    EMAILJS_PUBLIC_KEY,
    EMAILJS_REPORT_ERROR_TEMPLATE_ID,
    EMAILJS_SERVICE_ID,
    ONESIGNAL_APP_ID,
    REPOSITORY_URL,
    SITE_URL,
    SUPABASE_APY_KEY,
    SUPABASE_BUCKET,
    SUPABASE_ERRORS_FOLDER,
    SUPABASE_REVISITS_FOLDER,
    SUPABASE_URL,
} from '@env';

export const env = {
    BUGFENDER_API_KEY,
    EMAILJS_FEEDBACK_TEMPLATE_ID,
    EMAILJS_PUBLIC_KEY,
    EMAILJS_REPORT_ERROR_TEMPLATE_ID,
    EMAILJS_SERVICE_ID,
    REPOSITORY_URL,
    SITE_URL,
    SUPABASE_APY_KEY,
    SUPABASE_BUCKET,
    SUPABASE_ERRORS_FOLDER,
    SUPABASE_REVISITS_FOLDER,
    SUPABASE_URL,
    ONESIGNAL_APP_ID
}