export const env = {
    BUGFENDER_API_KEY: process.env.EXPO_PUBLIC_BUGFENDER_API_KEY,
    EMAILJS_FEEDBACK_TEMPLATE_ID: process.env.EXPO_PUBLIC_EMAILJS_FEEDBACK_TEMPLATE_ID,
    EMAILJS_PUBLIC_KEY: process.env.EXPO_PUBLIC_EMAILJS_PUBLIC_KEY,
    EMAILJS_REPORT_ERROR_TEMPLATE_ID: process.env.EXPO_PUBLIC_EMAILJS_REPORT_ERROR_TEMPLATE_ID,
    EMAILJS_SERVICE_ID: process.env.EXPO_PUBLIC_EMAILJS_SERVICE_ID,
    REPOSITORY_URL: process.env.EXPO_PUBLIC_REPOSITORY_URL,
    SITIE_URL: process.env.EXPO_PUBLIC_SITIE_URL,
    SUPABASE_APY_KEY: process.env.EXPO_PUBLIC_SUPABASE_APY_KEY,
    SUPABASE_BUCKET: process.env.EXPO_PUBLIC_SUPABASE_BUCKET,
    SUPABASE_ERRORS_FOLDER: process.env.EXPO_PUBLIC_SUPABASE_ERRORS_FOLDER,
    SUPABASE_REVISITS_FOLDER: process.env.EXPO_PUBLIC_SUPABASE_REVISITS_FOLDER,
    SUPABASE_SERVICE_ROLE_KEY: process.env.EXPO_PUBLIC_SUPABASE_SERVICE_ROLE_KEY,
    SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL,
    ONESIGNAL_APP_ID: process.env.EXPO_PUBLIC_ONESIGNAL_APP_ID
}